name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:$IMAGE_TAG .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:latest

    - name: Push the Docker image to Docker Hub
      run: |
        IMAGE_TAG=$(date +%s)
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:$IMAGE_TAG
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:latest
