name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Umgebung'
        required: true
        default: 'development'

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker image tag
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          IMAGE_TAG=$(date +%s)
        else
          IMAGE_TAG=${GITHUB_SHA::7}
        fi
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build and tag the Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:${{ env.IMAGE_TAG }} .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:latest

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:${{ env.IMAGE_TAG }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/counthomcfi:latest
